#!/bin/bash
# =============================================================================
# common.sh — shared constants and functions
# Sourced by setup.sh and test.sh — not run directly
# =============================================================================

BRANCH="scarthgap"
MACHINE="raspberrypi4-64"
DISTRO="rpi-headless"
META_CUSTOM_REPO="git@github.com:joe-stewart/meta-rpi-headless"

# =============================================================================
# clone_or_skip <name> <url> <base>
# Clones a layer at scarthgap if not already present
# =============================================================================

clone_or_skip() {
    local name=$1
    local url=$2
    local base=$3
    local dest="${base}/${name}"

    if [ -d "${dest}/.git" ]; then
        echo "  ${name}: already present, skipping"
    else
        echo "  ${name}: cloning..."
        git clone -b "${BRANCH}" "${url}" "${dest}"
    fi
}

# =============================================================================
# clone_all_layers <base>
# Clones all required layers into base
# =============================================================================

clone_all_layers() {
    local base=$1

    echo "Cloning layers (branch: ${BRANCH})..."
    echo ""
    clone_or_skip "poky"              "https://git.yoctoproject.org/poky"              "${base}"
    clone_or_skip "meta-openembedded" "https://github.com/openembedded/meta-openembedded" "${base}"
    clone_or_skip "meta-raspberrypi"  "https://github.com/agherzan/meta-raspberrypi" "${base}"
    clone_or_skip "meta-custom"       "${META_CUSTOM_REPO}"                           "${base}"
}

# =============================================================================
# write_bblayers <conf_dir> <base>
# Writes a populated bblayers.conf
# =============================================================================

write_bblayers() {
    local conf_dir=$1
    local base=$2

    cat > "${conf_dir}/bblayers.conf" << EOF
# =============================================================================
# bblayers.conf — layer stack for $(basename "$(dirname "${conf_dir}")")
# Generated by setup.sh — edit paths if your layout differs
# =============================================================================

BBPATH = "\${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \\
    ${base}/poky/meta \\
    ${base}/poky/meta-poky \\
    ${base}/meta-openembedded/meta-oe \\
    ${base}/meta-openembedded/meta-python \\
    ${base}/meta-openembedded/meta-networking \\
    ${base}/meta-raspberrypi \\
    ${SCRIPT_DIR} \\
"
EOF
}

# =============================================================================
# write_local_conf <conf_dir> <base> <sstate_dir>
# Writes a populated local.conf
# =============================================================================

write_local_conf() {
    local conf_dir=$1
    local base=$2
    local sstate_dir=$3

    cat > "${conf_dir}/local.conf" << EOF
# =============================================================================
# local.conf — $(basename "$(dirname "${conf_dir}")")
# Policy lives in meta-custom/conf/distro/rpi-headless.conf
# =============================================================================

MACHINE = "${MACHINE}"
DISTRO = "${DISTRO}"

LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

# --- Shared cache ------------------------------------------------------------
DL_DIR = "${base}/shared/downloads"
SSTATE_DIR = "${sstate_dir}"

# --- Parallelism — adjust to your core count ---------------------------------
BB_NUMBER_THREADS = "8"
PARALLEL_MAKE = "-j8"

# --- No busybox --------------------------------------------------------------
PREFERRED_PROVIDER_virtual/sh = "bash"

# --- Sanity ------------------------------------------------------------------
CONF_VERSION = "2"
EOF
}

# =============================================================================
# check_layers <base>
# Verifies all required layers are present
# =============================================================================

check_layers() {
    local base=$1
    local missing=0

    for layer in poky meta-openembedded meta-raspberrypi meta-custom; do
        if [ ! -d "${base}/${layer}/.git" ]; then
            echo "  ERROR: ${layer} not found at ${base}/${layer}"
            missing=1
        fi
    done

    return $missing
}
# =============================================================================
# write_firstboot_ini <base>
# Generates a ready-to-edit firstboot.ini in the base directory
# =============================================================================

write_firstboot_ini() {
    local base=$1
    local dest="${base}/firstboot.ini"

    if [ -f "${dest}" ]; then
        echo "  firstboot.ini already exists — skipping"
        return
    fi

    cat > "${dest}" << 'EOF'
# =============================================================================
# firstboot.ini — first boot configuration
# Copy to the root partition of the SD card before first boot:
#
#   sudo mkdir -p /tmp/root
#   sudo mount /dev/sdX2 /tmp/root
#   sudo cp firstboot.ini /tmp/root/firstboot.ini
#   sudo umount /tmp/root
#
# Processed once by firstboot.sh, deleted after. Root is locked on completion.
# To reconfigure: copy template to /firstboot.ini, delete /etc/firstboot.done,
# and reboot.
# =============================================================================

[user]
username=
password=
uid=1000

[ssh]
authorized_keys=

[hostname]
hostname=
EOF

    echo "  firstboot.ini written to ${dest}"
}
